- hosts: hadoop-all
  become: yes
  remote_user: vagrant
  vars:
    hostname :
      - 'hadoop-master'
      - 'hadoop-slave-1'
      - 'hadoop-slave-2'
      - 'hadoop-slave-3'
      - 'hadoop-slave-4'
  tasks:
    - name: Update file hosts
      copy: src=../init/files/hosts dest=/etc/hosts

    - name: Copy masters file
      copy: src=files/masters dest=/home/vagrant/hadoop/etc/hadoop/masters

    - name: Copy slaves file
      copy: src=files/slaves dest=/home/vagrant/hadoop/etc/hadoop/slaves

    - name: copy config files hadoop-env.sh
      copy: src=../hadoop/hadoop/hadoop-env.sh dest=/home/vagrant/hadoop/etc/hadoop/hadoop-env.sh

    - name: copy config files core-site.xml
      copy: src=../hadoop/hadoop/core-site.xml dest=/home/vagrant/hadoop/etc/hadoop/core-site.xml

    - name: copy config files hdfs-site.xml
      copy: src=../hadoop/hadoop/hdfs-site.xml dest=/home/vagrant/hadoop/etc/hadoop/hdfs-site.xml

    - name: copy config files yarn-site.xml
      copy: src=../hadoop/hadoop/yarn-site.xml dest=/home/vagrant/hadoop/etc/hadoop/yarn-site.xml

    - name: copy config files mapred-site.xml
      copy: src=../hadoop/hadoop/mapred-site.xml dest=/home/vagrant/hadoop/etc/hadoop/mapred-site.xml

    - name: Remove known_hosts
      command: rm -f /home/vagrant/.ssh/known_hosts

    - name: Make sure the known hosts file exists
      file: "path='/home/vagrant/.ssh/known_hosts' state=touch"

    - name: Change vagrant owner
      shell: chown vagrant:vagrant /home/vagrant/.ssh/known_hosts

    - name: Add known_hosts
      shell: ssh-keyscan {{ item }} >> /home/vagrant/.ssh/known_hosts
      with_items: hostname

    - name: Add publickey to server
      authorized_key:
        user: "vagrant"
        key: "{{ lookup('file', 'download/'+item+'/id_rsa.pub' ) }}"
      with_items: hostname